trekhleb/javascript-algorithms

- Readme.zh-TW.md
I translate the overview page from English into Mandarin
> add Mandarin overview

- src/algorithms/search/linear-search/Readme.md
- src/algorithms/search/linear-search/linearsearch.js
Added algorithm for the basic and useful linear search
> Added Linear Search

- src/data-structures/tree/segment-tree/README.md
- src/data-structures/tree/segment-tree/SegmentTree.js
- src/data-structures/tree/segment-tree/__test__/SegmentTree.test.js
Added src/data-structures/tree/segment-tree/SegmentTree.js and tests.
> Segment Tree implementation

- src/algorithms/string/z-algorithm/README.md
- src/algorithms/string/z-algorithm/__test__/zAlgorithm.test.js
- src/algorithms/string/z-algorithm/zAlgorithm.js
Implemented the Z algorithm, as requested in issue 54
> Z algorithm implementation

- README.ko_KR.md
- README.md
>  Translate to Korean

- README.md
- README.pl-PL.md
Adding a new file, and changing README.md file to add Polish language to the list of languages
> Translation to Polish

- README.fr-FR.md
- README.md
Hi @trekhleb,
I hereby submit a french translation of the repository (in its actual state).
Regards,
Roland.
> Add French translation

- src/data-structures/linked-list/LinkedList.js
Parameter 'deletedTail' were defined twice.
> Twice defined

- src/algorithms/string/rabin-karp/__test__/rabinKarp.test.js
- src/algorithms/string/rabin-karp/rabinKarp.js
- src/utils/hash/rolling/Rabin_Fingerprint.js
- src/utils/hash/rolling/__test__/Rabin_Fingerprint.test.js
* Simplify Rabin-Karp functionality
* Created Rabin Fingerprinting module within util directory
* Updated Rabin-Karp search to use rolling hash module
Incorporate tests from @dubzzz
> Refactor Rabin-Karp (#110)

- README.zh-CN.md
> Update README.zh-CN.md and Add date

- src/algorithms/math/bits/README.md
- src/algorithms/math/bits/countBitsToflipAToB.js
This adds implementation of counting bits to convert a number A to B using bitwise operators, dependency https://github.com/trekhleb/javascript-algorithms/pull/152.
> Add countBitsToflipAToB

- README.zh-CN.md
- src/data-structures/doubly-linked-list/README.zh-CN.md
- src/data-structures/graph/README.zh-CN.md
- src/data-structures/hash-table/README.zh-CN.md
- src/data-structures/heap/README.zh-CN.md
- src/data-structures/linked-list/README.zh-CN.md
- src/data-structures/priority-queue/README.zh-CN.md
- src/data-structures/queue/README.zh-CN.md
- src/data-structures/stack/README.zh-CN.md
- src/data-structures/tree/README.zh-CN.md
- src/data-structures/trie/README.zh-CN.md
Partial translation of Simplified Chinese
> Partial translation of Simplified Chinese

- src/data-structures/queue/Queue.js
This PR clarifies the comments in the Queue class.
Fixes issue: #192
> Clarify comments of Queue class

- src/data-structures/stack/Stack.js
The functions' comments were copied from Queue.js, but some words were not replaced.
I also made some changes to the wording for clarification.
> Improve JSDocs in Stack.js

- README.es-ES.md
Fixing multiple spelling issues in the Spanish readme, and improving some vocabulary to make it more in line with the names you might find in Spanish algorithms and data structures literature.
> Mutiple fixes in the spanish readme

- src/data-structures/linked-list/README.zh-CN.md
Add prepend operation and fix some mistake in pseudocode.
> Add prepend and fix bug

- src/algorithms/sorting/bubble-sort/BubbleSort.js
Use Destructuring assignment to swap values.
> BubbleSort: use Destructuring assignment to swap values

- src/data-structures/doubly-linked-list/README.md
- src/data-structures/doubly-linked-list/README.ru-RU.md
- src/data-structures/doubly-linked-list/README.zh-CN.md
I was a little bit confused when I saw those capital letters, are those need to fix?
> [Fix] Capitalization issues of doubly linked list.

- src/data-structures/linked-list/README.md
- src/data-structures/linked-list/README.ru-RU.md
- src/data-structures/linked-list/README.zh-CN.md
```shell
ag -l yeild |  xargs sed -i '' -e 's/yeild/yield/g'
```
> Fix typo: yeild => yield

- src/algorithms/math/bits/README.md
> fix README.md

- src/algorithms/string/levenshtein-distance/README.md
Fix for https://github.com/trekhleb/javascript-algorithms/issues/311
> Fix a spelling mistake in README.md for Levenshtein Distance

- src/data-structures/graph/README.pt-BR.md
The correct translation of graph to portuguese in this context is "Grafo".
"Gráfico" means a diagram showing the relation between variable quantities.
> Fix portuguese translation of graph on README

- README.zh-CN.md
There're some mistakes in the Chinese Translation. I've already corrected them. 
I also translated and updated the file. (Someone added machine-learning algorithm examples to the main README.md file)
> Fix and Update README.zh-CN.md

- README.pt-BR.md
adjusted for better reading of javascript-algorithms.
> set Data Structure to "Estrutura de Dados"

- README.ru-RU.md
README in the Russian language
> added README.ru-RU.md

- README.it-IT.md
This is an Italian Implementation of the Repository.
Let me know if you need other requirements for the contribution.
Thanks
Riccardo Amadio
> Italian Implementation

- README.md
- src/algorithms/math/prime-factors/README.md
- src/algorithms/math/prime-factors/__test__/primefactors.test.js
- src/algorithms/math/prime-factors/primefactors.js
An algorithm to compute total distinct count of prime factors for a given natural number using the approximate Hardy-Ramanujan algorithm and its comparison with the original accurate algorithm.
> added prime-factors algorithms under maths algorithms

- src/data-structures/doubly-linked-list/README.ko-KR.md
- src/data-structures/doubly-linked-list/README.md
* Translate doubly linked list document in Korean
* Update README.md
> Add doubly-linked-list doc in Korean

- README.id-ID.md
added README.id-ID.md that contains the translation for Bahasa Indonesia
> feat(lang): add README.id-ID.md translation for Bahasa Indonesia

- src/data-structures/linked-list/README.md
> Add missing step

- src/algorithms/string/levenshtein-distance/README.md
fix a grammatical typo in levenshtein-distance/README.md
> fix typo in levenshtein-distance/README.md

- src/data-structures/heap/README.md
- src/data-structures/heap/README.tr-TR.md
- Added Turkish translation of Heap (data structures) algorithm
> docs: add README.tr-TR.md

- src/data-structures/linked-list/README.pt-BR.md
Addition of slight grammatical corrections to documentation in PT-BR
> Addition of slight grammatical corrections

- README.tr-TR.md
- Fixed some typos and untranslated text on the Turkish README file.
- Added more descriptive descriptions  and keywords
> Fixed typos in the turkish and added descriptions

- src/algorithms/linked-list/reverse-traversal/README.md
- src/algorithms/linked-list/reverse-traversal/README.zh-CN.md
- src/algorithms/linked-list/traversal/README.md
- src/algorithms/linked-list/traversal/README.zh-CN.md
the chinese translation of traverse the linked list algorithm
> Add Chinese Translation

- README.id-ID.md
Just fixing typo in Bahasa Indonesia
> Typo in README.id-ID.md

- src/data-structures/stack/README.ko-KR.md
- src/data-structures/stack/README.md
translated README files to Korean and add link to original file
- src/data-structures/stack/README.ko-KR.md
- src/data-structures/stack/README.md
> Add Korean translation for data-structures/stack

- src/algorithms/math/factorial/README.md
- src/algorithms/math/factorial/README.tr-TR.md
Added Turkish readme for Factorial.
> Factorial turkish readme

- src/data-structures/linked-list/README.tr-TR.md
Turkish language support has been added for the linked list.
> Linked list turkish readme

- README.ja-JP.md
This PR is to change small modification in README.ja-JP.md.
> fix small modification in README.ja-JP.md

- LICENSE
Change Copy Write to 2021 from 2018.
> Update Copy Write to 2021

- src/data-structures/graph/README.fr-FR.md
- src/data-structures/graph/README.md
The first part of the translation is a direct translation of the
english part. The second is too, although it wasn't done by me
but by wikipedia contributors (the second paragraph of the
English wikipedia introduction is exactly the same as the first
paragraph of the French wikipedia "Description")
Add french version redirection on the README.md. The french
version is placed before the portuguese version to have a
cleaner diff (no trailing commas to edit)
> French translation for module "Graph"

- src/algorithms/sorting/merge-sort/README.ko-KR.md
- src/algorithms/sorting/merge-sort/README.md
- Add merge sort document in Korean
- Update README.md
> Add merge sort document in Korean

- README.md
Adding a link to the [Data Structure Sketches](https://okso.app/showcase/data-structures). It should give more visual context for those who learn data structures.
Here is a quick demo of the interactive sketches:
> Add a link to minimalistic data structure sketches.

- src/algorithms/search/binary-search/binarySearch.js
Fixed typo issue [!1064](https://github.com/trekhleb/javascript-algorithms/issues/1064)
> fix binary search typo

- src/data-structures/trie/README.ko-KO.md
- src/data-structures/trie/README.md
added korean translation for trie
> feat: added korean translation for trie

- src/algorithms/uncategorized/best-time-to-buy-sell-stocks/README.md
- src/algorithms/uncategorized/n-queens/README.md
- src/data-structures/bloom-filter/README.md
- src/data-structures/heap/Heap.js
> Fix four typos

- README.ar-AR.md
- README.de-DE.md
- README.es-ES.md
- README.fr-FR.md
- README.id-ID.md
- README.it-IT.md
- README.ja-JP.md
- README.ko-KR.md
- README.md
- README.pl-PL.md
- README.pt-BR.md
- README.ru-RU.md
- README.tr-TR.md
- README.uk-UA.md
- README.uz-UZ.md
- README.zh-CN.md
- README.zh-TW.md
Adding a new file, and changing README files to add Uzbek language to the list of languages
> feat: added uzbek language

- README.es-ES.md
This change is not much but i put the correct way that Fibonacci sequence is written in Spanish, i know that because i live in spain and i am a student and here we call it "Sucesión de Fibonacci"
> update the ES README a lenguage correction
