README.md

Just a typo fix in the README.

Fixed Typo in Big O Complexity table

---

README.zh-CN.md

Translate to Chinese

---

README.md
Readme.zh-TW.md

Finish main part of translation

Finish main part of translation

---

src/data-structures/trie/TrieNode.js
src/data-structures/trie/__test__/TrieNode.test.js

`Map` are more suitable and efficient for dynamically shaped hashes ([quick benchmark](https://repl.it/@caub/obj-vs-map-perf))

Use Map for TrieNode children

---

src/algorithms/math/fibonacci/__test__/fibonacci.test.js
src/algorithms/math/fibonacci/__test__/fibonacciNth.test.js
src/algorithms/math/fibonacci/fibonacciNth.js

The `fibonacci()` function now returns array of the fibonacci sequence, with the function `fibonacciNth()` returning the value at nth-position in the fibonacci sequence.

fibonacciNth function added

---

package-lock.json
src/algorithms/sets/knapsack-problem/Knapsack.js
src/algorithms/sets/knapsack-problem/__test__/Knapsack.test.js

fix unbound knapsack problem with items more than 1(default value)

---

src/algorithms/sorting/bubble-sort/README.md
src/algorithms/sorting/counting-sort/README.md
src/algorithms/sorting/heap-sort/README.md
src/algorithms/sorting/insertion-sort/README.md
src/algorithms/sorting/merge-sort/README.md
src/algorithms/sorting/quick-sort/README.md
src/algorithms/sorting/radix-sort/README.md
src/algorithms/sorting/selection-sort/README.md
src/algorithms/sorting/shell-sort/README.md

For the Sorting Algorithms, added their complexity in corresponding README.md

Added Complexity of Each Algorithm in Sorting/ directory.

---

src/algorithms/math/bits/README.md
src/algorithms/math/bits/getBit.js
src/algorithms/math/euclidean-algorithm/__test__/euclieanAlgorithm.test.js
src/algorithms/math/euclidean-algorithm/euclideanAlgorithm.js
src/algorithms/math/is-power-of-two/__test__/isPowerOfTwo.test.js
src/algorithms/math/is-power-of-two/__test__/isPowerOfTwoBitwise.test.js
src/algorithms/math/is-power-of-two/isPowerOfTwo.js
src/algorithms/math/is-power-of-two/isPowerOfTwoBitwise.js
src/algorithms/math/least-common-multiple/leastCommonMultiple.js
src/algorithms/sets/fisher-yates/fisherYates.js

Minor fixes/improvements to a small number of basic algorithms.

Minor fixes.

---

src/data-structures/doubly-linked-list/DoublyLinkedList.js
src/data-structures/doubly-linked-list/DoublyLinkedListNode.js
src/data-structures/doubly-linked-list/README.md
src/data-structures/doubly-linked-list/__test__/DoublyLinkedList.test.js
src/data-structures/doubly-linked-list/__test__/DoublyLinkedListNode.test.js

Doubly linked list with the same methods that are used in singly linked list. Tests are also added.

Added doubly linked list

---

src/algorithms/sorting/counting-sort/CountingSort.js
src/algorithms/sorting/counting-sort/__test__/CountingSort.test.js

When trying to run property based tests on the sorting algorithms available in javascript-algorithms, I detected sorting issues on CountingSort and RadixSort with arrays having negative entries.
Here is a fix to be able to handle negative integers in CountingSort.
The commit adding property based tests to the sorting algorithms is available at https://github.com/dubzzz/javascript-algorithms/commit/34b0c46df41fc18ab839be8c8bdece556d3b5d70
If you are interested in such testing approach I can issue another pull request to add those tests too.

Fix CountingSort for negative numbers

---

src/algorithms/string/rabin-karp/__test__/rabinKarp.test.js
src/algorithms/string/rabin-karp/rabinKarp.js
src/utils/hash/rolling/Rabin_Fingerprint.js
src/utils/hash/rolling/__test__/Rabin_Fingerprint.test.js

Created Rabin hash function module.
Transitioned Rabin-Karp string matching function to Rabin hash function family.

Refactor Rabin-Karp

---

README.pt-BT.md

Hi, trekhleb.
A loved this repository, so I translated it to Portuguese, Brazil.

Translated into Portuguese, Brazil.

---

src/algorithms/math/bits/README.md
src/algorithms/math/bits/__test__/countSetBits.test.js
src/algorithms/math/bits/countSetBits.js

This adds implementation of counting set bits in a number using bitwise operators.

Add countSetBits

---

jest.config.js

Solution: https://github.com/facebook/jest/issues/6769

Issue 169 test suite failed fix

---

src/data-structures/trie/Trie.js
src/data-structures/trie/__test__/Trie.test.js

Method Trie::doesWordExist() return `true` when word is complete otherwise `false`

Fix method Trie::doesWordExist()

---

src/data-structures/trie/TrieNode.js
src/data-structures/trie/__test__/Trie.test.js

Currently when adding a substring of an existing word, the new word does not get marked as a complete word. Here's an example:
```js
const trie = new Trie();
trie.addWord('javascript');
trie.addWord('java');
trie.doesWordExist('java'); // returns false
```
This PR fixes the issue.

Fix TrieNode.addChild so substrings get marked as complete words

---

src/data-structures/trie/Trie.js
src/data-structures/trie/TrieNode.js
src/data-structures/trie/__test__/Trie.test.js
src/data-structures/trie/__test__/TrieNode.test.js

This PR adds the ability to delete words from the Trie data structure.
**NOTE - when deleting a word:**
- sets `trieNode.isCompleteWord` to `false` for the last character in the word
- deletes trieNodes in depth-first order (last character -> first character) 
- does NOT delete trieNodes if they have children
- does NOT delete trieNodes if `trieNode.isCompleteWord === true` (this is to prevent substring words from being deleted)
Example usage:
```js
const trie = new Trie();
trie.addWord('carpet');
trie.addWord('car');
trie.deleteWord('carpet');
trie.doesWordExist('carpet'); // returns false
trie.doesWordExist('car'); // returns true
```
Issue: #108
Refactored From PR: #168

Feature: Add Trie.deleteWord and TrieNode.removeChild

---

src/data-structures/tree/segment-tree/README.md

Fixed a minor typo on `segment-tree` readme file:
- [`fins` => `find`](https://github.com/trekhleb/javascript-algorithms/compare/master...klauscfhq:master#diff-5c4ba01d9a803eba5858038fa21435f6)

Fix minor typo on `segment-tree` readme

---

src/algorithms/string/longest-common-substring/__test__/longestCommonSubstring.test.js
src/algorithms/string/longest-common-substring/longestCommonSubstring.js

A have fixed the `longestCommonSubstring` to handle unicode characters by spliting the string into an array of one character strings.

fix longestCommonSubstring() to handle unicode characters (#129)

---

src/data-structures/heap/Heap.js

In the Heap implementation, I noticed a few areas that could be cleaned up, including:
- typos
- MinHeap-specific comments
- minor refactoring for simplification

clean up Heap implementation

---

src/data-structures/linked-list/README.md
src/data-structures/linked-list/__test__/LinkedList.test.js

**Changes:**
* Add assert condition to LinkedList append test
* Add pseudocode document for LinkedList prepend

Update LinkedList prepend pseudocode and append test

---

src/algorithms/sets/maximum-subarray/dpMaximumSubarray.js

Alternate PR to #160 
**Changes:**
- Remove special case handling of array with all negative numbers
- Keep track of start/end indices and return a copy of `maxSubarray` at the end, rather than keeping a greedy copy of `maxSubarray`

Simplify dpMaximumSubarray

---

src/data-structures/linked-list/LinkedList.js
src/data-structures/linked-list/README.md
src/data-structures/linked-list/__test__/LinkedList.test.js

**Changes:**
- Add LinkedList traverse implementation
- Add LinkedList reverse implementations (reverseTraversal and reverse)
- Update their pseudocode

Add LinkedList traversal and reverse implementations

---

src/algorithms/math/bits/README.md
src/algorithms/math/bits/__test__/isPositive.test.js
src/algorithms/math/bits/isPositive.js
src/algorithms/math/bits/multiply.js

Bitwise operations used to determine if a number is positive

feat(bitwise): Function to check if a number is positive

---

src/algorithms/sorting/quick-sort/QuickSortInPlace.js

I added some additional comments for explanation, and simplified a few things.

Minor refactor of QuickSortInPlace for simplification

---

README.zh-CN.md

In China, we usually call it 'KMP算法', 
So I chose to use a free translation instead of a literal translation.
And I may submit content about Chinese translations more frequently recently.
PS: the editor fixed some problems of having extra spaces at the end of several lines.

change '克努斯-莫里斯-普拉特算法' to 'KMP算法'

---

src/data-structures/stack/Stack.js
src/data-structures/stack/__test__/Stack.test.js

* By definition Stack push/pop time complexity should be O(1).
* Fix is applied by removing head instead of tail in pop method.
* Push method now do preprend instead of append.
* Fix consistency between toString and toArray methods.

Fix Stack pop comlexity to be O(1)

---

README.es-ES.md

When comparing the Spanish and English readmes, I noticed there were some algorithms missing in the spanish one.

Adding missing algorithms in the spanish readme

---

src/data-structures/doubly-linked-list/DoublyLinkedList.js
src/data-structures/doubly-linked-list/__test__/DoublyLinkedList.test.js

fixed doubly-linked-list reverse method omit change node's previous

---

src/algorithms/sorting/quick-sort/QuickSortInPlace.js

Change argument of `this.callbacks.visitingCallback()`
Issue: #312

Fix performance measuring code bug

---

src/algorithms/math/bits/README.md
src/algorithms/math/bits/__test__/fullAdder.test.js
src/algorithms/math/bits/fullAdder.js

This method adds up two integer numbers using bitwise operators.
It implements [full adder](https://en.wikipedia.org/wiki/Adder_(electronics)) electronics circut logic to sum two 32-bit integers in two's complement format. It's using the boolean logic to cover all possible cases of adding two input bits: with and without a "carry bit" from adding the previous less-significant stage.
Legend:
- `A`: Number `A`
- `B`: Number `B`
- `ai`: ith bit of number `A`
- `bi`: ith bit of number `B`
- `carryIn`: a bit carried in from the previous less-significant stage
- `carryOut`: a bit to carry to the next most-significant stage
- `bitSum`: The sum of `ai`, `bi`, and `carryIn`
- `resultBin`: The full result of adding current stage with all less-significant stages (in binary)
- `resultBin`: The full …

Add Full Adder algorithm (math/bits)

---

src/data-structures/tree/segment-tree/README.md
src/data-structures/tree/segment-tree/README.pt-BR.md

`sam` should be `sum` as a type of range query, which is correctly spelled in the test file.

Fix README typo

---

src/algorithms/string/caeserCipher/README.md
src/algorithms/string/caeserCipher/__test__/caeserCipher.test.js
src/algorithms/string/caeserCipher/caeserCipher.js
src/algorithms/string/z-algorithm/README.md

Hi @trekhleb. I just added the ceaserCipher algorithm to your javascript-algorithms repository and it is well tested and documented, I would like you to merge it with the existing repository. Thanks in advance

Caeser cipher

---

src/data-structures/tree/binary-search-tree/README.md

only when root != ø, inner traverse code could be executed

fix: three errors

---

src/algorithms/sorting/merge-sort/MergeSort.js

The previous implementation of merge sort used the array.shift() method to merge elements from leftArray and rightArray into the sorted array. This is a bad practice, because JavaScript's implementation of the Array.prototype.shift() method is, at worst, O(n) runtime complexity, where n is the length of the array being sorted (in order to move n elements of an array over by 1, all n elements of the array must typically be touched).
To work around this, I refactored merge sort to use array pointers instead. Now, after an element has been added to the sorted array, rather than delete it from the old array and shift the entire old array over, the array index pointer is just incremented to the right by one to avoid the old element. This will always require O(1) runtime complexity, which is a …

Refactored merge sort to use array pointers instead of .shift()

---

src/algorithms/math/horner-method/README.md
src/algorithms/math/horner-method/__test__/hornerMethod.test.js
src/algorithms/math/horner-method/hornerMethod.js

Added Horner's Method into algorithms/math. Horner's method is a clever solution named after William George Horner, to evaluate polynomial functions given a certain point. I think it would be an interesting addition since it can be used in many hardware/software applications.

Add Horner's Method

---

src/algorithms/tree/breadth-first-search/__test__/breadthFirstSearch.test.js

There was a small typo in the name of one of the tests.

Fix typo in tree BFS testcase name

---

src/data-structures/tree/red-black-tree/RedBlackTree.js

Simple change to fix the typo in a comment in RedBlackTree.js
This is to address issue #528

Fix typo in comment

---

src/data-structures/hash-table/HashTable.js
src/data-structures/hash-table/__test__/HashTable.test.js

Add a getValues() method to the HashTable data structure

Modify HashTable

---

README.md
src/algorithms/ML/KNN/README.md
src/algorithms/ML/KNN/__test__/knn.test.js
src/algorithms/ML/KNN/knn.js

Hi Oleksii,
I've created a folder for ML in algorithms and added KNN to it. Added tests in __tests__ folder, and they are running with full code coverage. I have created a README explaining the algorithm. Also I've added KNN to the main README with link. Please do have a look and tell if anything else needs to be done. 
Thanks,
Avi

Adding K Nearest Neighbor to ML folder in algorithms with README and tests   

---

src/algorithms/sorting/insertion-sort/InsertionSort.js
src/algorithms/sorting/insertion-sort/__test__/InsertionSort.test.js

The existing insertion sort implementation began by iterating from
0 until the end of the array, but it is only necessary to
iterate from 1 until the end of the array, since at the
0th index, there is nothing to compare to the left of
the element.
I also corrected the grammar/wording of the comments.
In order to complete this change, I also had to update the tests
to reflect the fact that the algorithm visits each index 1 less
time.
Passed all tests and linting.

Optimize Insertion Sort, update tests, & correct comments

---

README.ar-AR.md
README.de-DE.md
README.es-ES.md
README.fr-FR.md
README.id-ID.md
README.it-IT.md
README.ja-JP.md
README.ko-KR.md
README.md
README.pl-PL.md
README.pt-BR.md
README.ru-RU.md
README.tr-TR.md
README.uk-UA.md
README.zh-CN.md
README.zh-TW.md

I have left the English names of the algorithms in round brackets. Nobody uses the German terms in everyday life. They are used at universities, but never at work. But they help to understand. This is a good compromise. Unfortunately, there are also some that have never been given a German name. Then I didn't invent one either. I have tried to use only official terminology. That is, from specialist literature, Wikipedia, etc. To keep it consistent, a purely English name appears twice.

add german translation for main readme

---

src/data-structures/linked-list/README.md

When `n.next = tail` is true, we assign `n` to `tail` and `null` to `tail.next`, so `n.next` also becomes `null`. Then we assign `n.next.next` (because now `n.next` is `null`), we try to get `next` of `null`. That is why we should add an `else` case to check if `n.next` is not equal to `tail`.

Null Reference Exception

---

README.pt-BR.md

General formatting and translation fixes

Fixes README.pt-BR.md

---

README.ja-JP.md

Grammar change and "Block " to "Jump"

---

README.zh-CN.md

纠正不准确的中文翻译 - dynamic programming.

Correct inaccurate Chinese translation.

---

.editorconfig

In VSCode with prettier extension the format on save changes automatically to double quotes, so I add one line in .editorconfig to prevent it.

Adding single quotes type to editorconfig

---

README.md
src/algorithms/sets/power-set/README.md
src/algorithms/sets/power-set/__test__/caPowerSet.test.js
src/algorithms/sets/power-set/caPowerSet.js

We already have [Bitwise](https://github.com/trekhleb/javascript-algorithms/blob/master/src/algorithms/sets/power-set/bwPowerSet.js) and [BackTracking](https://github.com/trekhleb/javascript-algorithms/blob/master/src/algorithms/sets/power-set/btPowerSet.js) solutions.
However, the `Cascading` solution described in this PR might be easier to understand. It is just about two `for` loops, with no recursion.

Adding a simple cascading solution to generate a Power Set
